version: '3'

services:

  seaweedfs_master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_master
    ports:
      - 9333:9333
    command: "master"
    networks:
      - suncity

  seaweedfs_volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs_volume
    ports:
      - 8080:8080
    volumes:
      - ../fs_data:/data
    command: 'volume -max=5 -mserver="seaweedfs_master:9333" -port=8080'
    depends_on:
      - seaweedfs_master
    networks:
      - suncity

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - suncity

  memcached:
    image: memcached
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - suncity

  postgres:
    image: postgres:9.6
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ../db_data:/var/lib/postgres/data/pgdata
    environment:
      - POSTGRES_USER=suncity
      - POSTGRES_PASSWORD=wearetheword
      - POSTGRES_DB=suncity
      - PGDATA=/var/lib/postgres/data/pgdata
    networks:
      - suncity

networks:
  suncity:
