# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.1.0"
  title: 修订考勤记录

# Describe your paths here
paths:
  /revise_clocks:
    post:
      description: 创建修订考勤记录接口
      tags:
        - 修订考勤记录
      parameters:
        - name: revise_clock_params
          in: body
          required: true
          description: 创建参数
          schema:
            $ref: '#/definitions/ReviseClockCreateParams'
      responses:
        200:
          description: 成功响应
          schema:
            $ref: '#/definitions/EmptyData'
    get:
      description: 获取修订考勤记录列表
      tags:
        - 修订考勤记录
      parameters:
        - name: date
          in: query
          required: false
          type: string
          description: 申请时间
        - name: chinese_name
          in: query
          required: false
          type: string
          description: 申请人中文名
        - name: user_chinese_name
          in: query
          required: false
          type: string
          description: 查询的员工姓名
        - name: department_chinese_name
          in: query
          required: false
          type: string
          description: 查询的部门名称
        - name: position_chinese_name
          in: query
          required: false
          type: string
          description: 查询的职位名称
        - name: record_type
          in: query
          required: false
          type: string
          description: 申请类型
        - name: item_count
          in: query
          required: false
          type: string
          description: 记录数目
        - name: status
          in: query
          required: false
          type: string
          description: 申请状态
        - name: creator_chinese_name
          in: query
          required: false
          type: string
          description: 录入人中文姓名
        - name: created_at
          in: query
          required: false
          type: string
          description: 录入日期
        - name: sort_direction
          in: query
          required: false
          type: string
          description: 排序方向
        - name: sort_column
          in: query
          required: false
          type: string
          description: 排序字段
      responses:
        200:
          description: 响应修订考勤记录列表

  /revise_clocks/{revise_clock_id}:
    get:
      description: 获取修订考勤记录信息
      tags:
        - 修订考勤记录
      parameters:
        - name: revise_clock_id
          in: path
          required: true
          type: integer
          description: 修订考勤记录ID
      responses:
        200:
          description: 响应修订考勤记录信息
  /revise_clocks/field_options:
    get:
      description: 获取记录列表可供筛选的字段
      tags:
        - 修订考勤记录
      responses:
        200:
          description: 成功响应

  # /revise_clocks/{revise_clock_id}/revise_clock_items:
  #   get:
  #     description: 获取修订考勤记录排班项目
  #     tags:
  #       - 修订考勤记录
  #     parameters:
  #       - name: revise_clock_id
  #         in: path
  #         required: true
  #         type: integer
  #         description: 修订考勤记录ID
  #     responses:
  #       200:
  #         description:  获取修订考勤记录排班项目

definitions:
  ReviseClockCreateParams:
    type: object
    properties:
      user_id:
        type: string
        description: 员工的user_id
      comment:
        type: string
        description: 备注
      date:
        type: string
        description: 日期
      revise_clock_items:
        type: array
        items:
          type: object
          properties:
            user_id:
              type: integer
              description: 员工id
            clock_date:
              type: string
              description: 日期
            clock_in_time:
              type: string
              description: 原上班打卡日期时间
            clock_out_time:
              type: string
              description: 原下班打卡日期时间
            attendance_state:
              type: array
              items:
                type: integer
              description: 原状态id
            new_clock_in_time:
              type: string
              description: 修改后的打卡日期时间
            new_clock_out_time:
              type: string
              description: 修改后的打卡日期时间
            new_attendance_state:
              items:
                type: integer
              description: 新状态id
            comment:
              type: string
              description: 备注
        description: 创建修订考勤记录数组
      attend_approvals:
        type: array
        items:
          type: object
          properties:
            user_id:
              type: integer
              description: 审批人id
            date:
              type: string
              description: 审批时间 2017-01-10
            comment:
              type: string
              description: 审批建议
        description: 创建修订考勤记录审批记录
      attend_attachments:
        type: array
        items:
          type: object
          properties:
            file_name:
              type: string
              description: 附件名称 'fn.jpg'
            comment:
              type: string
              description: 附件备注 'test comment'
            attachment_id:
              type: integer
              description: 附件id
        description: 修订考勤记录附件

  EmptyData:
    type: object
    properties:
      data:
        type: array
        items:
          title: 空数组
      meta:
        type: array
        items:
          title: 空数组