annual_bonus_items:
  columns:
    - key: employee_id
      value_type: string_value
      data_index: user.empoid
      search_type: search
      sorter: true
      search_attribute: user.empoid

    - key: employee_name
      value_type: obj_value
      data_index: user
      search_type: search
      sorter: true

    - key: department
      value_type: obj_value
      data_index: user.department
      search_type: screen
      sorter: true
      options_type: options
      options_action: department_options
      search_attribute: user.department_id

    - key: position
      value_type: obj_value
      data_index: user.position
      search_type: screen
      sorter: true
      options_type: options
      options_action: position_options
      search_attribute: user.position_id

    - key: career_entry_date
      value_type: date_value
      data_index: user.profile.data.position_information.field_values.date_of_employment
      value_format: yyyy/mm/dd
      search_type: date
      search_attribute: user.profile.position_information.date_of_employment
      sorter: true

    - key: has_annual_incentive_payment
      value_type: bool_value
      search_type: screen
      sorter: true
      options_type: predefined
      options_predefined:
        - key: true
          chinese_name: 是
          english_name: YES
          simple_chinese_name: 是
        - key: false
          chinese_name: 否
          english_name: NO
          simple_chinese_name: 否

    - key: annual_incentive_payment_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: has_double_pay
      value_type: bool_value
      search_type: screen
      sorter: true
      options_type: predefined
      options_predefined:
        - key: true
          chinese_name: 是
          english_name: YES
          simple_chinese_name: 是
        - key: false
          chinese_name: 否
          english_name: NO
          simple_chinese_name: 否

    - key: double_pay_mop
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: has_year_end_bonus
      value_type: bool_value
      search_type: screen
      sorter: true
      options_type: predefined
      options_predefined:
        - key: true
          chinese_name: 是
          english_name: YES
          simple_chinese_name: 是
        - key: false
          chinese_name: 否
          english_name: NO
          simple_chinese_name: 否

    - key: year_end_bonus_mop
      value_type: string_value
      search_type: decimal_range
      sorter: true
