dismission_salary_items:
  columns:
    - key: dimission_date
      value_type: date_value
      value_format: yyyy/mm/dd
      data_index: dimission.last_work_date
      search_type: date
      sorter: true

    - key: employee_id
      value_type: string_value
      data_index: user.empoid
      search_type: search
      sorter: true
      search_attribute: user.empoid

    - key: employee_name
      value_type: obj_value
      data_index: user
      search_type: search
      sorter: true

    - key: company
      value_type: obj_value
      data_index: user.company_name
      search_type: screen
      sorter: true
      options_type: selects
      options_select_key: company_name
      search_attribute: user.company_name

    - key: department
      value_type: obj_value
      value_format: null
      data_index: user.department
      search_type: screen
      sorter: true
      options_type: options
      options_action: department_options
      search_attribute: user.department_id

    - key: position
      value_type: obj_value
      value_format: null
      data_index: user.position
      search_type: screen
      sorter: true
      options_type: options
      options_action: position_options
      search_attribute: user.position_id

    - key: grade
      value_type: string_value
      data_index: user.grade
      search_type: screen
      sorter: true
      options_type: selects
      options_select_key: grade
      search_attribute: user.grade

    - key: dimission_type
      value_type: select_value
      data_index: dimission.dimission_type
      search_type: screen
      sorter: true
      options_type: selects
      options_select_key: dimission_type
      search_attribute: dimission.dimission_type

    - key: dimission_reason
      value_type: select_value
      data_index: dimission.career_history_dimission_reason
      search_type: screen
      sorter: true
      options_type: selects
      options_select_key: reason_for_resignation
      search_attribute: dimission.career_history_dimission_reason

    - key: has_seniority_compensation
      value_type: select_value
      search_type: screen
      sorter: true
      options_type: predefined
      options_predefined:
        - key: true
          chinese_name: 是
          english_name: YES
          simple_chinese_name: 是
        - key: false
          chinese_name: 否
          english_name: NO
          simple_chinese_name: 否

    - key: has_inform_period_compensation
      value_type: select_value
      search_type: screen
      sorter: true
      options_type: predefined
      options_predefined:
        - key: true
          chinese_name: 是
          english_name: YES
          simple_chinese_name: 是
        - key: false
          chinese_name: 否
          english_name: NO
          simple_chinese_name: 否

    - key: base_salary_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: benefits_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: annual_incentive_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: housing_benefits_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: seniority_compensation_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: dismission_annual_holiday_compensation_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true

    - key: dismission_inform_period_compensation_hkd
      value_type: string_value
      search_type: decimal_range
      sorter: true
