reserved_holiday_participators:
  columns:
    - key: reserved_holiday_setting
      value_type: obj_value
      data_index: reserved_holiday_setting
      search_type: screen
      sorter: true
      options_type: options
      options_action: setting_options
      search_attribute: reserved_holiday_setting.chinese_name

    - key: empoid
      value_type: string_value
      data_index: user.empoid
      search_type: search
      sorter: true
      search_attribute: user.empoid

    - key: name
      value_type: obj_value
      data_index: user
      search_type: search
      sorter: true
      search_attribute: user.chinese_name

    - key: department
      value_type: obj_value
      data_index: user.department
      search_type: screen
      sorter: true
      options_type: options
      options_action: department_options
      search_attribute: user.department_id

    - key: position
      value_type: obj_value
      data_index: user.position
      search_type: screen
      sorter: true
      options_type: options
      options_action: position_options
      search_attribute: user.position_id

    - key: employment_status
      value_type: obj_value
      data_index: user.employment_status
      search_type: screen
      sorter: true
      options_type: selects
      options_select_key: employment_status
      search_attribute: user.employment_status

    - key: grade
      value_type: string_value
      data_index: user.grade
      search_type: screen
      sorter: true
      options_type: options
      options_action: grade_options
      search_attribute: user.grade

    - key: date_of_employment
      value_type: date_value
      value_format: yyyy/mm/dd
      data_index: user.profile.data.position_information.field_values.date_of_employment
      search_type: date
      sorter: true

    - key: owned_days_count
      value_type: string_value
      data_index: owned_days_count
      search_type: search
      sorter: true

    - key: taken_days_count
      value_type: string_value
      data_index: taken_days_count
      search_type: search
      sorter: true