cover_charge:
  chinese_name: 超級管理員組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 招聘組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 考勤組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 薪酬組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 職位變動組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 藍卡組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 員工關係組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 培訓組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: 部門主管組
  english_name: Cover charge
  simple_chinese_name: 茶资
cover_charge:
  chinese_name: VP級數據權限組
  english_name: Cover charge
  simple_chinese_name: 茶资
