salary_records:
  columns:
    - key: empoid
      value_type: string_value
      data_index: user.empoid
      sorter: true

    - key: name
      value_type: obj_value
      data_index: user
      sorter: true

    - key: company_name
      value_type: obj_value
      data_index: user.company_name
      sorter: true

    - key: division_of_job
      value_type: select_value
      data_index: user.profile.data.position_information.field_values.division_of_job
      sorter: true
      options_type: selects
      options_select_key: division_of_job
      option: division_of_job

    - key: location
      value_type: obj_value
      data_index: user.location
      sorter: true

    - key: department
      value_type: obj_value
      data_index: user.department
      sorter: true

    - key: position
      value_type: obj_value
      data_index: user.position
      sorter: true

    - key: grade
      value_type: string_value
      data_index: user.grade
      sorter: true

    - key: date_of_employment
      value_type: string_value
      data_index: user.profile.data.position_information.field_values.date_of_employment
      sorter: true

    - key: leave_date
      value_type: string_value
      data_index: user.profile.data.position_information.field_values.resigned_date
      sorter: true

    - key: salary_begin
      data_index: salary_begin
      value_type: date_value
      value_format: yyyy/mm/dd
      sorter: true

    - key: change_reason
      data_index: change_reason
      value_type: select_value
      options_type: selects
      options_select_key: deployment_type
      option: deployment_type


    - key: type_of_id
      data_index: user.profile.data.personal_information.field_values.type_of_id
      value_type: select_value
      options_type: selects
      options_select_key: type_of_id
      option: type_of_id

    - key: basic_salary
      data_index: final_basic_salary
      value_type: string_value

    - key: bonus
      data_index: final_bonus
      value_type: string_value

    - key: attendance_award
      data_index: final_attendance_award
      value_type: string_value

    - key: house_bonus
      data_index: final_house_bonus
      value_type: string_value

    - key: region_bonus
      data_index: final_region_bonus
      value_type: string_value

    - key: tea_bonus
      data_index: final_tea_bonus
      value_type: string_value

    - key: kill_bonus
      data_index: final_kill_bonus
      value_type: string_value

    - key: performance_bonus
      data_index: final_performance_bonus
      value_type: string_value

    - key: charge_bonus
      data_index: final_charge_bonus
      value_type: string_value

    - key: commission_bonus
      data_index: final_commission_bonus
      value_type: string_value

    - key: receive_bonus
      data_index: final_receive_bonus
      value_type: string_value

    - key: exchange_rate_bonus
      data_index: final_exchange_rate_bonus
      value_type: string_value

    - key: guest_card_bonus
      data_index: final_guest_card_bonus
      value_type: string_value

    - key: respect_bonus
      data_index: final_respect_bonus
      value_type: string_value

    - key: new_year_bonus
      data_index: final_new_year_bonus
      value_type: string

    - key: project_bonus
      data_index: final_project_bonus
      value_type: string_value

    - key: product_bonus
      data_index: final_product_bonus
      value_type: string_value

    - key: service_award
      data_index: final_service_award
      value_type: string_value

    - key: internship_bonus
      data_index: final_internship_bonus
      value_type: string_value

    - key: performance_award
      data_index: final_performance_award
      value_type: string_value

    - key: special_tie_bonus
      data_index: final_special_tie_bonus
      value_type: string_value