special_schedule_remarks:
  columns:
    - key: empoid
      value_type: string_value
      data_index: user.empoid
      search_type: search
      search_attribute: user.empoid
      sorter: true

    - key: name
      value_type: obj_value
      data_index: user
      search_type: search
      sorter: true

    - key: department
      value_type: obj_value
      data_index: user.department
      sorter: true
      options_type: options
      options_action: department_options
      search_attribute: user.department_id

    - key: position
      value_type: obj_value
      data_index: user.position
      sorter: true
      options_type: options
      options_action: position_options
      search_attribute: user.position_id

    - key: date_of_employment
      value_type: date_value
      value_format: yyyy/mm/dd
      data_index: user.profile.data.position_information.field_values.date_of_employment
      search_type: date
      sorter: true

    - key: content
      value_type: string_value
      data_index: content

    - key: date_begin
      value_type: date_value
      value_format: yyyy/mm/dd
      data_index: date_begin
      search_type: date
      sorter: true

    - key: date_end
      value_type: date_value
      value_format: yyyy/mm/dd
      data_index: date_end
      search_type: date
      sorter: true

