student_evaluations:
  columns:
    - key: empoid
      data_index: user.empoid
      value_type: string_value
      sorter: true
      search_type: search
      search_attribute: user.empoid

    - key: name
      data_index: user
      value_type: obj_value
      sorter: true
      search_type: search

    - key: department
      data_index: user.department
      value_type: obj_value
      sorter: true
      search_type: screen
      options_type: options
      options_action: department_options
      search_attribute: user.department_id

    - key: position
      data_index: user.position
      value_type: obj_value
      sorter: true
      search_type: screen
      options_type: options
      options_action: position_options
      search_attribute: user.position_id

