training_absentees:
  columns:
    - key: employee_id
      value_type: string_value
      data_index: user.empoid
      search_type: search
      sorter: true
      search_attribute: user.empoid

    - key: employee_name
      value_type: obj_value
      data_index: user
      search_type: search
      sorter: true

    - key: department
      value_type: obj_value
      value_format: null
      data_index: user.department
      search_type: screen
      sorter: true
      options_type: options
      options_action: department_options
      search_attribute: user.department_id

    - key: position
      value_type: obj_value
      value_format: null
      data_index: user.position
      search_type: screen
      sorter: true
      options_type: options
      options_action: position_options
      search_attribute: user.position_id

    - key: train_name
      value_type: obj_value
      data_index: train_class.train
      search_type: screen
      sorter: true
      options_type: options
      options_action: train_name_options
      search_attribute: train_classes.train_id

    - key: train_number
      value_type: number_value
      data_index: train_class.train.train_number
      search_attribute: train.train_number
      search_type: search
      sorter: true
      search_attribute: trains.train_number

    - key: train_date
      value_type: date_value
      data_index: train_class.train
      value_format: 'YYYY/MM/DD ~ YYYY/MM/DD'
      search_type: date
      sorter: true
      search_attribute: trains.train_date_begin

    - key: has_submitted_reason
      value_type: bool_value
      search_type: screen
      sorter: true
      options_type: predefined
      options_predefined:
        - key: true
          chinese_name: 已提交
          english_name: Submitted
          simple_chinese_name: 已提交
        - key: false
          chinese_name: 未提交
          english_name: Unsubmitted
          simple_chinese_name: 未提交

    - key: has_been_exempted
      value_type: bool_value
      search_type: screen
      sorter: true
      options_type: predefined
      options_predefined:
        - key: true
          chinese_name: 是
          english_name: YES
          simple_chinese_name: 是
        - key: false
          chinese_name: 否
          english_name: NO
          simple_chinese_name: 否

    - key: train_class_time
      value_type: date_value
      data_index: train_class
      value_format: 'A) YYYY/MM/DD 星期* hh:mm-hh:mm'
      search_type: date
      sorter: true
      search_attribute: train_classes.time_begin

    - key: absence_reason
      value_type: string_value

    - key: submit_date
      value_type: date_value
      value_format: 'YYYY/MM/DD hh:mm'
      search_type: date
      sorter: true